{{- if and .Values.monitoring.enabled .Values.monitoring.hubMetrics.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hub-metrics
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      component: hub
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.monitoring.namespace }}
      ports:
        - protocol: TCP
          port: 8081
{{- end }}
