#!/usr/bin/env python3
# Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
"""Render deployment artifacts from resolved configuration values."""

from __future__ import annotations

from config_common import DEFAULT_ACCEL_LABELS, HEADER_HASH, die, require, yaml_quote
from gpu_access_resolution import FleetResolution, HostStatus


def render_inventory(spec: dict, token: str, resolution: FleetResolution) -> str:
    topo = spec["topology"]
    server = spec["server"]
    k3s_version = spec["k3s_version"]
    host_gpu_enabled = {host.target.name: host.status is HostStatus.GPU for host in resolution.hosts}
    lines = [
        HEADER_HASH,
        "k3s_cluster:",
        "  children:",
        "    server:",
        "      hosts:",
        f"        {server['name']}:",
        f"          ansible_host: {yaml_quote(server['ip'])}",
        f"          auplc_gpu_access_enabled: {'true' if host_gpu_enabled[server['name']] else 'false'}",
        "    agent:",
    ]
    if topo == "ssh-preinstalled" and spec.get("agents"):
        lines.append("      hosts:")
        for agent in spec["agents"]:
            lines.append(f"        {agent['name']}:")
            lines.append(f"          ansible_host: {yaml_quote(agent['ip'])}")
            lines.append(
                f"          auplc_gpu_access_enabled: {'true' if host_gpu_enabled[agent['name']] else 'false'}"
            )
    else:
        lines.append("      hosts: {}")
    lines += [
        "  vars:",
        "    ansible_port: 22",
        "    ansible_user: root",
        f"    k3s_version: {yaml_quote(k3s_version)}",
        f"    token: {yaml_quote(token)}",
        "    api_endpoint: \"{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}\"",
    ]
    if topo == "pxe-diskless":
        lines += [
            "",
            "pxe_controller:",
            "  hosts:",
            f"    {server['name']}:",
            f"      ansible_host: {yaml_quote(server['ip'])}",
            "  vars:",
            "    ansible_port: 22",
            "    ansible_user: root",
        ]
    return "\n".join(lines) + "\n"


def render_pxe_vars(spec: dict, pxe_gpu_access_enabled: bool) -> str:
    net = require(spec, "network")
    pxe = spec.get("pxe", {})
    keys = pxe.get("authorized_keys", [])
    if not keys:
        die("pxe.authorized_keys must contain at least one SSH public key")
    server_ip = spec["server"]["ip"]
    k3s_version = spec["k3s_version"]
    lines = [
        HEADER_HASH,
        "# Pass this file to pb-pxe-controller.yml with",
        "# ansible-playbook ... -e @<absolute-path-to-this-file>",
        "# pxe_k3s_version is pinned to k3s_version so agents are never newer",
        "# than the server.",
        "pxe_rootfs_force_rebuild: true   # first build only; set false afterwards",
        f"pxe_network_interface: {yaml_quote(net['interface'])}",
        f"pxe_subnet: {yaml_quote(net['subnet'])}",
        f"pxe_gateway: {yaml_quote(net.get('gateway', ''))}",
        f"pxe_dns_servers: {yaml_quote(net.get('dns_servers', '8.8.8.8,8.8.4.4'))}",
        f"pxe_controller_ip: {yaml_quote(server_ip)}",
        "pxe_k3s_server_ips:",
        f"  - {yaml_quote(server_ip)}",
        f"pxe_k3s_version: {yaml_quote(k3s_version)}",
        f"pxe_gpu_access_enabled: {'true' if pxe_gpu_access_enabled else 'false'}",
        f"pxe_web_port: {int(pxe.get('web_port', 8080))}",
        f"pxe_rootfs_password: {yaml_quote(pxe.get('rootfs_password', ''))}",
        "pxe_rootfs_authorized_keys:",
    ]
    for key in keys:
        lines.append(f"  - {yaml_quote(key)}")
    return "\n".join(lines) + "\n"


def render_values(spec: dict, auth_providers: tuple[str, ...]) -> str:
    accel = spec.get("accelerators") or {}
    storage_class = (spec.get("storage") or {}).get("class", "nfs-client")
    node_port = (spec.get("proxy") or {}).get("node_port", 30890)
    images = spec.get("images") or {}
    lines = [
        "# Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.",
        "# Helm overlay generated by auplc-skills gen_configs.py.",
        "# Layer this on top of runtime/values.yaml:",
        "#   helm upgrade --install jupyterhub ./runtime/chart -n jupyterhub \\",
        "#     --create-namespace -f runtime/values.yaml -f <this file>",
        "custom:",
        "  auth:",
    ]
    lines.extend(f"    {provider}: true" for provider in auth_providers)
    lines += [
        "  runtimeLimitEnabled: true",
        "  quota:",
        "    enabled: true",
    ]
    if accel:
        lines.append("  accelerators:")
        for key, config in accel.items():
            product = (config or {}).get("product_name") or DEFAULT_ACCEL_LABELS.get(key)
            if not product:
                die(
                    f"accelerator '{key}' has no product_name and no known default; "
                    "add accelerators.<key>.product_name from `kubectl describe node`"
                )
            lines += [
                f"    {key}:",
                "      nodeSelector:",
                f"        amd.com/gpu.product-name: {yaml_quote(product)}",
            ]
    if accel or images:
        lines.append("  resources:")
    if accel:
        lines += ["    metadata:", "      gpu:", "        acceleratorKeys:"]
        lines.extend(f"          - {yaml_quote(key)}" for key in accel)
    if images:
        lines.append("    images:")
        for key, value in images.items():
            lines.append(f"      {key}: {yaml_quote(value)}")
    lines += [
        "hub:",
        "  db:",
        "    pvc:",
        f"      storageClassName: {yaml_quote(storage_class)}",
        "singleuser:",
        "  storage:",
        "    dynamic:",
        f"      storageClass: {yaml_quote(storage_class)}",
        "proxy:",
        "  service:",
        "    type: NodePort",
        "    nodePorts:",
        f"      http: {int(node_port)}",
    ]
    return "\n".join(lines) + "\n"
