#!/usr/bin/env python3
# Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
"""Shared schema constants and scalar rendering helpers."""

from __future__ import annotations

import json
import sys

HEADER_HASH = (
    "# Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.\n"
    "# Generated by auplc-skills gen_configs.py -- review before use.\n"
)

DEFAULT_ACCEL_LABELS = {
    "phx": "AMD_Radeon_780M_Graphics",
    "strix": "AMD_Radeon_890M_Graphics",
    "strix-halo": "AMD_Radeon_8060S_Graphics",
    "9070xt": "AMD_Radeon_RX_9070_XT",
    "r9700": "AMD_Radeon_AI_PRO_R9700",
    "9600gre": "AMD_Radeon_RX_9600_GRE",
}


class DuplicateJsonKeyError(ValueError):
    pass


def _unique_json_object(pairs):
    document = {}
    for key, value in pairs:
        if key in document:
            raise DuplicateJsonKeyError(f"duplicate JSON key '{key}'")
        document[key] = value
    return document


def strict_json_loads(raw: str):
    return json.loads(raw, object_pairs_hook=_unique_json_object)


def die(msg: str, code: int = 1) -> None:
    print(f"gen_configs: {msg}", file=sys.stderr)
    raise SystemExit(code)


def require(spec: dict, path: str):
    cur = spec
    for part in path.split("."):
        if not isinstance(cur, dict) or part not in cur or cur[part] in (None, "", []):
            die(f"spec is missing required field '{path}'")
        cur = cur[part]
    return cur


def yaml_quote(value: str) -> str:
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'
