#!/usr/bin/env python3
# Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
"""Generate AUP Learning Cloud deploy artifacts from a small cluster-spec.

Given a JSON cluster-spec (see ``--print-schema``), write the three files the
deploy skill needs, keeping them mutually consistent:

  1. ``inventory.yml``               -- Ansible inventory (server + token +
                                        k3s_version; agents listed for the
                                        SSH topology, empty for PXE).
  2. ``pb-pxe-controller.vars.yml``  -- PXE topology only: extra vars passed to
                                        pb-pxe-controller.yml with
                                        ``-e @<absolute-path>``.
  3. ``values-basic-example.yaml``   -- Helm overlay: accelerator nodeSelectors,
                                        storage class, proxy NodePort, authMode.

Design choices (deliberate):

  * stdlib only (json, argparse, secrets, base64, pathlib). No PyYAML, so this
    runs on a bare operator machine. YAML is emitted from templates, not a
    serialiser -- the output is small, fixed-shape, and carries the copyright header.
  * The k3s token is generated locally with ``secrets`` (CSPRNG) and written
    ONLY into inventory.yml. It is never printed to stdout/stderr. Pass
    ``--token-file`` to reuse an existing token instead of minting one.
  * ``pxe_k3s_version`` is forced equal to ``k3s_version`` so agents can never
    be newer than the server (k3s refuses that).
  * Existing files are not overwritten unless ``--force`` is given.

Usage:
    gen_configs.py --print-schema
    gen_configs.py --spec spec.json --out-dir ./generated
    cat spec.json | gen_configs.py --spec - --out-dir ./generated --force

Exit codes: 0 on success; 1 on a spec/validation error; 2 on a usage error.
"""

from __future__ import annotations

import argparse
import base64
import json
import os
import secrets
import shutil
import sys
import tempfile
from contextlib import suppress
from pathlib import Path

HEADER_HASH = (
    "# Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.\n"
    "# Generated by auplc-skills gen_configs.py -- review before use.\n"
)

# Default GPU product-name labels, keyed by the accelerator key used in
# runtime/values.yaml (custom.accelerators.<key>). Verified against the chart's
# values.yaml; override per fleet via spec["accelerators"][key]["product_name"].
DEFAULT_ACCEL_LABELS = {
    "phx": "AMD_Radeon_780M_Graphics",
    "strix": "AMD_Radeon_890M_Graphics",
    "strix-halo": "AMD_Radeon_8060S_Graphics",
    "9070xt": "AMD_Radeon_RX_9070_XT",
    "r9700": "AMD_Radeon_AI_PRO_R9700",
    "9600gre": "AMD_Radeon_RX_9600_GRE",
}

SCHEMA = {
    "topology": "pxe-diskless | ssh-preinstalled",
    "k3s_version": "v1.32.3+k3s1",
    "server": {"name": "aipc1", "ip": "192.168.0.140"},
    "agents": [{"name": "aipc2", "ip": "192.168.0.141"}],
    "network": {
        "interface": "enp1s0",
        "subnet": "192.168.0.0/24",
        "gateway": "192.168.0.1",
        "dns_servers": "8.8.8.8,8.8.4.4",
    },
    "pxe": {
        "authorized_keys": ["ssh-ed25519 AAAA... you@host"],
        "rootfs_password": "",
        "web_port": 8080,
    },
    "accelerators": {"strix-halo": {"product_name": "AMD_Radeon_8060S_Graphics"}},
    "storage": {"class": "nfs-client"},
    "proxy": {"node_port": 30890},
    "auth_mode": "auto-login",
    "images": {"cpu": "ghcr.io/amdresearch/auplc-default:latest", "gpu": "ghcr.io/amdresearch/auplc-base:latest"},
}


def die(msg: str, code: int = 1) -> None:
    print(f"gen_configs: {msg}", file=sys.stderr)
    raise SystemExit(code)


def gen_token() -> str:
    # Mirror `openssl rand -base64 64`: 64 random bytes, base64-encoded.
    return base64.b64encode(secrets.token_bytes(64)).decode("ascii")


def require(spec: dict, path: str):
    cur = spec
    for part in path.split("."):
        if not isinstance(cur, dict) or part not in cur or cur[part] in (None, "", []):
            die(f"spec is missing required field '{path}'")
        cur = cur[part]
    return cur


def yaml_quote(s: str) -> str:
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def validate_accelerators(spec: dict) -> None:
    if "accelerators" not in spec:
        return
    accelerators = spec["accelerators"]
    if not isinstance(accelerators, dict):
        die("spec.accelerators must be a mapping")
    unsupported = sorted(set(accelerators) - set(DEFAULT_ACCEL_LABELS))
    if len(unsupported) == 1:
        die(f"unsupported accelerator key '{unsupported[0]}'")
    if unsupported:
        die(f"unsupported accelerator keys: {', '.join(unsupported)}")
    for key, config in accelerators.items():
        if not isinstance(config, dict):
            die(f"accelerators.{key} must be a mapping")


def validate_config_shapes(spec: dict) -> None:
    if not isinstance(spec, dict):
        die("spec must be a mapping")
    validate_accelerators(spec)
    for key in ("network", "pxe", "storage", "proxy", "images"):
        if key in spec and not isinstance(spec[key], dict):
            die(f"spec.{key} must be a mapping")


def render_inventory(spec: dict, token: str) -> str:
    topo = spec["topology"]
    server = spec["server"]
    k3s_version = spec["k3s_version"]
    lines = [
        HEADER_HASH,
        "k3s_cluster:",
        "  children:",
        "    server:",
        "      hosts:",
        f"        {server['name']}:",
        f"          ansible_host: {server['ip']}",
        "    agent:",
    ]
    if topo == "ssh-preinstalled" and spec.get("agents"):
        lines.append("      hosts:")
        for a in spec["agents"]:
            lines.append(f"        {a['name']}:")
            lines.append(f"          ansible_host: {a['ip']}")
    else:
        # PXE diskless agents auto-join by netboot; do NOT list them here.
        lines.append("      hosts: {}")
    lines += [
        "  vars:",
        "    ansible_port: 22",
        "    ansible_user: root",
        f"    k3s_version: {k3s_version}",
        f"    token: {yaml_quote(token)}",
        "    api_endpoint: \"{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}\"",
    ]
    if topo == "pxe-diskless":
        lines += [
            "",
            "pxe_controller:",
            "  hosts:",
            f"    {server['name']}:",
            f"      ansible_host: {server['ip']}",
            "  vars:",
            "    ansible_port: 22",
            "    ansible_user: root",
        ]
    return "\n".join(lines) + "\n"


def render_pxe_vars(spec: dict) -> str:
    net = require(spec, "network")
    pxe = spec.get("pxe", {})
    keys = pxe.get("authorized_keys", [])
    if not keys:
        die("pxe.authorized_keys must contain at least one SSH public key")
    server_ip = spec["server"]["ip"]
    k3s_version = spec["k3s_version"]
    lines = [
        HEADER_HASH,
        "# Pass this file to pb-pxe-controller.yml with",
        "# ansible-playbook ... -e @<absolute-path-to-this-file>",
        "# pxe_k3s_version is pinned to k3s_version so agents are never newer",
        "# than the server.",
        "pxe_rootfs_force_rebuild: true   # first build only; set false afterwards",
        f"pxe_network_interface: {yaml_quote(net['interface'])}",
        f"pxe_subnet: {yaml_quote(net['subnet'])}",
        f"pxe_gateway: {yaml_quote(net.get('gateway', ''))}",
        f"pxe_dns_servers: {yaml_quote(net.get('dns_servers', '8.8.8.8,8.8.4.4'))}",
        f"pxe_controller_ip: {yaml_quote(server_ip)}",
        "pxe_k3s_server_ips:",
        f"  - {yaml_quote(server_ip)}",
        f"pxe_k3s_version: {yaml_quote(k3s_version)}",
        f"pxe_web_port: {int(pxe.get('web_port', 8080))}",
        f"pxe_rootfs_password: {yaml_quote(pxe.get('rootfs_password', ''))}",
        "pxe_rootfs_authorized_keys:",
    ]
    for k in keys:
        lines.append(f"  - {yaml_quote(k)}")
    return "\n".join(lines) + "\n"


def render_values(spec: dict) -> str:
    accel = spec.get("accelerators") or {}
    storage_class = (spec.get("storage") or {}).get("class", "nfs-client")
    node_port = (spec.get("proxy") or {}).get("node_port", 30890)
    auth_mode = spec.get("auth_mode", "auto-login")
    images = spec.get("images") or {}

    lines = [
        "# Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.",
        "# Helm overlay generated by auplc-skills gen_configs.py.",
        "# Layer this on top of runtime/values.yaml:",
        "#   helm upgrade --install jupyterhub ./runtime/chart -n jupyterhub \\",
        "#     --create-namespace -f runtime/values.yaml -f <this file>",
        "custom:",
        f"  authMode: {yaml_quote(auth_mode)}",
    ]
    if accel:
        lines.append("  accelerators:")
        for key, cfg in accel.items():
            product = (cfg or {}).get("product_name") or DEFAULT_ACCEL_LABELS.get(key)
            if not product:
                die(
                    f"accelerator '{key}' has no product_name and no known default; "
                    "add accelerators.<key>.product_name from `kubectl describe node`"
                )
            lines += [
                f"    {key}:",
                "      nodeSelector:",
                f"        amd.com/gpu.product-name: {yaml_quote(product)}",
            ]
    if accel or images:
        lines.append("  resources:")
    if accel:
        lines += ["    metadata:", "      gpu:", "        acceleratorKeys:"]
        lines.extend(f"          - {yaml_quote(key)}" for key in accel)
    if images:
        lines.append("    images:")
        for k, v in images.items():
            lines.append(f"      {k}: {yaml_quote(v)}")
    lines += [
        "hub:",
        "  db:",
        "    pvc:",
        f"      storageClassName: {yaml_quote(storage_class)}",
        "singleuser:",
        "  storage:",
        "    dynamic:",
        f"      storageClass: {yaml_quote(storage_class)}",
        "proxy:",
        "  service:",
        "    type: NodePort",
        "    nodePorts:",
        f"      http: {int(node_port)}",
    ]
    return "\n".join(lines) + "\n"


def preflight_destinations(paths: list[Path], force: bool) -> None:
    if force:
        return
    for path in paths:
        if os.path.lexists(path):
            die(f"refusing to overwrite existing {path} (use --force)", 1)


def stage_file(path: Path, content: str, mode: int) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, staged_path = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        os.fchmod(fd, mode)
        with os.fdopen(fd, "w", encoding="utf-8") as staged_file:
            staged_file.write(content)
            staged_file.flush()
            os.fsync(staged_file.fileno())
    except OSError:
        with suppress(OSError):
            os.close(fd)
        Path(staged_path).unlink(missing_ok=True)
        raise
    return Path(staged_path)


def remove_destination(path: Path) -> None:
    if path.is_dir() and not path.is_symlink():
        shutil.rmtree(path)
    else:
        path.unlink(missing_ok=True)


def backup_destination(path: Path) -> tuple[Path, Path]:
    backup_dir = Path(tempfile.mkdtemp(prefix=f".{path.name}.backup.", dir=path.parent))
    backup_path = backup_dir / path.name
    os.replace(path, backup_path)
    return backup_dir, backup_path


def publish_artifacts(artifacts: list[tuple[Path, str, int, bool]], force: bool) -> None:
    staged: list[tuple[Path, Path, bool]] = []
    published: list[Path] = []
    backups: list[tuple[Path, Path, Path]] = []
    try:
        for path, content, mode, secret in artifacts:
            staged.append((path, stage_file(path, content, mode), secret))
        for path, staged_path, secret in staged:
            if force and os.path.lexists(path):
                backup_dir, backup_path = backup_destination(path)
                backups.append((path, backup_dir, backup_path))
            if force:
                os.replace(staged_path, path)
            else:
                os.link(staged_path, path)
                os.unlink(staged_path)
            published.append(path)
            print(f"wrote {path}" + ("  (chmod 600 -- contains the k3s token)" if secret else ""))
    except OSError as exc:
        for path in reversed(published):
            remove_destination(path)
        for path, backup_dir, backup_path in reversed(backups):
            remove_destination(path)
            os.replace(backup_path, path)
            backup_dir.rmdir()
        die(f"could not publish generated artifacts: {exc}")
    else:
        for _, backup_dir, _ in backups:
            shutil.rmtree(backup_dir)
    finally:
        for _, staged_path, _ in staged:
            staged_path.unlink(missing_ok=True)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--spec", help="path to the cluster-spec JSON, or - for stdin")
    ap.add_argument("--out-dir", default="generated", help="directory to write artifacts into (default: ./generated)")
    ap.add_argument("--token-file", help="read the k3s token from this file instead of generating one")
    ap.add_argument("--force", action="store_true", help="overwrite existing files")
    ap.add_argument("--print-schema", action="store_true", help="print an example cluster-spec and exit")
    args = ap.parse_args(argv)

    if args.print_schema:
        print(json.dumps(SCHEMA, indent=2))
        return 0
    if not args.spec:
        die("--spec is required (or use --print-schema)", 2)

    raw = sys.stdin.read() if args.spec == "-" else Path(args.spec).read_text(encoding="utf-8")
    try:
        spec = json.loads(raw)
    except json.JSONDecodeError as exc:
        die(f"spec is not valid JSON: {exc}")

    if not isinstance(spec, dict):
        die("spec must be a mapping")
    topo = spec.get("topology")
    if topo not in ("pxe-diskless", "ssh-preinstalled"):
        die("spec.topology must be 'pxe-diskless' or 'ssh-preinstalled'")
    require(spec, "k3s_version")
    require(spec, "server.name")
    require(spec, "server.ip")
    validate_config_shapes(spec)

    if args.token_file:
        token = Path(args.token_file).read_text(encoding="utf-8").strip()
        if not token:
            die("--token-file is empty")
    else:
        token = gen_token()

    out = Path(args.out_dir)
    artifacts = [(out / "inventory.yml", render_inventory(spec, token), 0o600, True)]
    if topo == "pxe-diskless":
        artifacts.append((out / "pb-pxe-controller.vars.yml", render_pxe_vars(spec), 0o600, False))
    artifacts.append((out / "values-basic-example.yaml", render_values(spec), 0o644, False))
    preflight_destinations([path for path, _, _, _ in artifacts], args.force)
    publish_artifacts(artifacts, args.force)

    print(
        "\nNext: review the files, then copy them into your aup-learning-cloud "
        "checkout. Never commit inventory.yml -- it holds the k3s token."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
